// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUkVDBCibf23ZyeVxB_8UYnDlhVularg',
    appId: '1:209716118926:web:3457c150a3248d4fc590df',
    messagingSenderId: '209716118926',
    projectId: 'porteiroeletronico-sel0373',
    authDomain: 'porteiroeletronico-sel0373.firebaseapp.com',
    storageBucket: 'porteiroeletronico-sel0373.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8i8tEFjBhNYJXDIg1v67risppWb1QRAI',
    appId: '1:209716118926:android:70d45d1bf1159e0bc590df',
    messagingSenderId: '209716118926',
    projectId: 'porteiroeletronico-sel0373',
    storageBucket: 'porteiroeletronico-sel0373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNFXQEusscDhCpKpbn5zT0C9OQJCNGSg8',
    appId: '1:209716118926:ios:37da8a10ec210db1c590df',
    messagingSenderId: '209716118926',
    projectId: 'porteiroeletronico-sel0373',
    storageBucket: 'porteiroeletronico-sel0373.appspot.com',
    iosClientId:
        '209716118926-ufhsoo9rp1ispl7qt4bc1fq9mndlvpus.apps.googleusercontent.com',
    iosBundleId: 'com.example.sel0373',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNFXQEusscDhCpKpbn5zT0C9OQJCNGSg8',
    appId: '1:209716118926:ios:37da8a10ec210db1c590df',
    messagingSenderId: '209716118926',
    projectId: 'porteiroeletronico-sel0373',
    storageBucket: 'porteiroeletronico-sel0373.appspot.com',
    iosClientId:
        '209716118926-ufhsoo9rp1ispl7qt4bc1fq9mndlvpus.apps.googleusercontent.com',
    iosBundleId: 'com.example.sel0373',
  );
}
